remote_theme: just-the-docs/just-the-docs
title: Voron Resources

callouts_level: quiet # or loud
callouts:
  highlight:
    color: yellow
  important:
    title: Important
    color: blue
  new:
    title: New
    color: green
  note:
    title: Note
    color: purple
  warning:
    title: Warning
    color: red

markdown: kramdown
kramdown:
  input: GFM

# aux_links:
#   "HASHI on GitHub":
#     - "https://github.com/RIVeR-Lab/hashi/tree/main"

nav_external_links:
  - title: Additional Resources
    url: https://github.com/PARSES-Lab/voron-resources

back_to_top: true
back_to_top_text: "Back to top"